plv/Controllers/DocsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
//using plv.BlockModels;
using plv.Models;
using plv.Data;
using plv.ViewModels;

namespace plv.Controllers
{
    [Authorize(Roles = "User, Admin")]
    public class DocsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ApplicationDbContext _context;

        public DocsController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager, ApplicationDbContext _context)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            this._context = _context;
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        [Route("Docs/Create/{sectionName}")]
        public IActionResult Create(string sectionName)
        {
            ApplicationUser currentUser = _userManager.FindByNameAsync(User.Identity.Name).Result;
            if (!_userManager.IsInRoleAsync(currentUser, sectionName + "-upload").Result)
            {
                return RedirectToAction("DocSections");
            }

            UploadFileViewModel viewModel = new UploadFileViewModel()
            {
                Section = sectionName
            };
            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(UploadFileViewModel model)
        {
            string selectedSectionName = model.Section;
            if (String.IsNullOrEmpty(selectedSectionName))
            {
                model.Success = false;
                model.LogMessage = "Wybierz sekcję dokumentów";
                return RedirectToAction("Create");
            }

            if(String.IsNullOrEmpty(model.Receiver) && String.IsNullOrEmpty(model.Sender))
            {
                model.Success = false;
                model.LogMessage = "Wypełnij pola nadawcy/odbiorcy";
                return RedirectToAction("Create");
            }

            if(model.DateReceived == null)
            {
                model.Success = false;
                model.LogMessage = "Wybierz datę otrzymania";
                return RedirectToAction("Create");
            }

            if (model.File != null)
            {
                string fileName = GetUniqueFileName(model.File.FileName, model.Section);

                CreateUploadDirectoryIfDoesNotExist();
                CreateSectionDirectoryIfDoesNotExist(selectedSectionName);

                string savePath = Path.Combine(Directory.GetCurrentDirectory(),
                    $"wwwroot/uploads/{selectedSectionName}",
                    fileName);

                if (Path.GetExtension(savePath) != ".pdf")
                {
                    model.Success = false;
                    model.LogMessage = "Plik musi być plikiem .pdf";
                }
                else
                {
                    using (var stream = new FileStream(savePath, FileMode.Create))
                    {
                        if (model.Sender == null)
                        {
                            model.Sender = "";
                        }
                        else if (model.Receiver == null)
                        {
                            model.Receiver = "";
                        }
                        if(model.ShortOptionalDescription == null)
                        {
                            model.ShortOptionalDescription = "";
                        }
                        model.File.CopyTo(stream); model.Success = true;
                        model.LogMessage = "Dokument dodany";
                        SaveDocumentToDB(fileName, selectedSectionName, model);

                    }
                }
            }
            return View("Create", model);
        }

        [Route("Docs/Details/{id}")]
        public IActionResult Details(int id)
        {
            DocumentInDB doc = _context.Documents.Find(id);

           // List<string> invalidBlocksFields = ValidateFirstBlock(doc);

            DocumentDetailsViewModel viewModel = new DocumentDetailsViewModel
            {
                Document = doc,
                IsOwnedByCurrentUser = (doc.CurrentUser == User.Identity.Name) ? true : false,
              //  InvalidBlocksFieldsList = invalidBlocksFields
            };


            return View(viewModel);
        }



        [Route("Docs/Download/{sectionName}/{filename}")]
        public IActionResult DownloadDocument(string sectionName, string filename)
        {
            if (filename == null)
                return Content("filename not present");

            string currentUserName = User.Identity.Name;

            ApplicationUser currentUser = _userManager.FindByNameAsync(User.Identity.Name).Result;
            if (!_userManager.IsInRoleAsync(currentUser, sectionName + "-download").Result && !_userManager.IsInRoleAsync(currentUser, "Admin").Result)
            {
                return Content("you can't download in this section");
            }
            else
            {
                try
                {
                    var path = Path.Combine(
                                   Directory.GetCurrentDirectory(),
                                   $"wwwroot/uploads/{sectionName}", filename);
                    var memory = new MemoryStream();
                    using (var stream = new FileStream(path, FileMode.Open)) { stream.CopyTo(memory); }
                    memory.Position = 0;
                    SaveDownloadLog(currentUserName, sectionName, filename);
                    return File(memory, GetContentType(path), Path.GetFileName(path));
                }
                catch (Exception e)
                {
                    return NotFound();
                }
            }
        }

        [Route("Docs/DocsList/{sectionName}")]
        public IActionResult DocsList(string sectionName)
        {
            ApplicationUser currentUser = _userManager.FindByNameAsync(User.Identity.Name).Result;
            if (!_userManager.IsInRoleAsync(currentUser, sectionName).Result && !_userManager.IsInRoleAsync(currentUser, "Admin").Result)
            {
                return Content("you can't browse in this section");
            }

            List<DocumentInDB> docs = _context.Documents.Where(c => c.Section == $"{sectionName}").ToList();

            DocumentListViewModel viewModel = new DocumentListViewModel
            {
                Documents = docs,
                CurrentSection = sectionName
            };

            return View(viewModel);
        }

        public IActionResult DocSections()
        {
            var sections = _context.Sections.ToList();
            return View(sections);
        }

        [Route("Docs/DownloadHistory/{filename}")]
        [Authorize(Roles = "Admin")]
        public IActionResult DownloadHistory(string filename)
        {
            List<Downloads> downloadLog = new List<Downloads>();
            if (filename == "all")
            {
                downloadLog = _context.Downloads.ToList();
            }
            else
            {
                downloadLog = _context.Downloads.Where(x => x.FileName == filename).ToList();
            }


            return View(downloadLog);
        }

        [Route("Docs/Edit/{id}")]
        public IActionResult Edit(int id)
        {
            DocumentInDB doc = _context.Documents.Find(id);

            List<ApplicationUser> currentSectionUsers = GetCurrentSectionUsers(doc.Section);
            EditDocumentViewModel viewModel = new EditDocumentViewModel
            {
                Document = doc,
                Users = currentSectionUsers
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditDoc(EditDocumentViewModel model)
        {
            string currentUserName = User.Identity.Name;
            var docInDB = _context.Documents.Single(c => c.Id == model.Document.Id);

            SaveDocEdits(currentUserName, docInDB, model);


            if (!String.IsNullOrEmpty(model.Document.Receiver))
            {
                docInDB.Receiver = model.Document.Receiver;
            }
            else
            {
                docInDB.Receiver = "";
            }
            if (!String.IsNullOrEmpty(model.Document.Sender))
            {
                docInDB.Sender = model.Document.Sender;
            }
            else
            {
                docInDB.Sender = "";
            }
            if(String.IsNullOrEmpty(model.Document.ShortOptionalDescription))
            {
                model.Document.ShortOptionalDescription = "";
            }
            docInDB.ShortOptionalDescription = model.Document.ShortOptionalDescription;
            docInDB.CurrentUser = model.Document.CurrentUser;
            if (model.Document.DateReceived != null && model.Document.DateReceived != DateTime.MinValue)
            {
                docInDB.DateReceived = model.Document.DateReceived;
            }


            _context.SaveChanges();

         //   UpdateFirstBlock(docInDB);

            return Redirect($"Details/{model.Document.Id}");
        }

        [Route("Docs/EditHistory/{id}")]
        [Authorize(Roles = "Admin")]
        public IActionResult EditHistory(int? id)
        {
            List<DocEdits> history = new List<DocEdits>();
            if (id == null || id == 0)
            {
                history = _context.DocumentEdits.ToList();
            }
            else
            {

plv/Views/Shared/_AdminSidebar.cshtml
<h1>
    <a class="logo" asp-area="" asp-controller="Home" asp-action="Index"><img class="link-image" src="~/images/home.svg" /></a>
</h1>
<ul class="list-unstyled components">
    <li>
        <a class="btn btn-outline-info" asp-area="" asp-controller="Docs" asp-action="DocSections"><img class="link-image" src="~/images/docs.svg" /><br /> Dokumenty</a>
    </li>
    <li>
        <a class="btn btn-outline-info" asp-area="" asp-controller="Admin" asp-action="UserList"><img class="link-image" src="~/images/userlist.svg" /><br />Użytkownicy</a>
    </li>
    <li>
        <a class="btn btn-outline-info" asp-area="" asp-controller="Admin" asp-action="SectionList"><img class="link-image" src="~/images/seclist.svg" /><br />Lista sekcji</a>
    </li>
</ul>

<partial name="_SidebarLoginPartial" />

plv/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - plv</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min-slate.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/datatables/datatables.min.css" />
</head>
<body>

    @if (this.User.IsInRole("Admin"))
    {
        <partial name="_adminNavBar" />
    }
    else
    {
        <partial name="_navBar" />
    }



    <div class="main-content">
        <main role="main">
            <div class="row">
                <div class="col-md-1">
                    @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Admin"))
                    {
                        <nav id="sidebar" class="active">
                            <partial name="_AdminSidebar" />
                        </nav>
                    }
                    else if (this.User.Identity.IsAuthenticated && !this.User.IsInRole("Admin"))
                    {
                        <nav id="sidebar" class="active">
                            <partial name="_Sidebar" />
                        </nav>
                    }
                </div>
                @RenderBody()
            </div>

        </main>
    </div>



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="~/datatables/datatables.min.js"></script>
    <script type="text/javascript" src="~/bootbox/bootbox.all.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

plv/Views/Shared/_Sidebar.cshtml
<h1>
    <a class="logo" asp-area="" asp-controller="Home" asp-action="Index"><img class="link-image" src="~/images/home.svg" /></a>
</h1>
<ul class="list-unstyled components">
    <li>
        <a class="btn btn-outline-info" asp-area="" asp-controller="Docs" asp-action="DocSections"><img class="link-image" src="~/images/docs.svg" /><br />Dokumenty</a>
    </li>
</ul>

<partial name="_SidebarLoginPartial" />

plv/Views/Shared/_SidebarLoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using plv.Models
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="navbar-right">
        <ul class="list-unstyled components">
            <li>
                <a class="btn btn-outline-info mt-auto" asp-area="" asp-controller="Account" asp-action="Manage" title="Manage"><img class="link-image" src="~/images/manageacc2.svg" /><br />Konto</a>
            </li>
            <li>
                <button class="btn btn-outline-info plvlight" type="submit"><img class="link-image" src="~/images/logout2.svg" /></button>
            </li>
        </ul>
    </form>
}
else
{
    <ul class="list-unstyled components">
        <li><a asp-area="" asp-controller="Account" asp-action="Register">Rejestracja</a></li>
        <li><a asp-controller="Account" asp-action="Login">Logowanie</a></li>
    </ul>
}

plv/Views/Shared/_adminNavBar.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Docs" asp-action="DocSections">Dokumenty</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Admin" asp-action="UserList">Użytkownicy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Admin" asp-action="SectionList">Lista sekcji</a>
                    </li>
                </ul>

            </div>
            <partial name="_LoginPartial" />
        </div>
    </nav>
</header>

plv/Views/Shared/_navBar.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow">
        <div class="container">
            <!--<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">plv</a>-->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Docs" asp-action="DocSections">Dokumenty</a>
                    </li>
                </ul>

            </div>
            <partial name="_LoginPartial" />
        </div>
    </nav>
</header>